import 'package:admin/data/models/domain/report_definition.dart';
import 'package:admin/data/models/domain/report_payload.dart';
import 'package:admin/domain/entity_type.dart';
import 'package:admin/domain/reports/report_engine.dart';

/// Report → the tag type its rows carry (React #3251). Every report listed
/// here offers the Tags filter (`tag_ids`, which the server applies to every
/// export — `BaseExport`); line-item reports take their document's tags.
const Map<String, String> kReportTagEntityTypes = {
  'client': 'client',
  'invoice': 'invoice',
  'invoice_item': 'invoice',
  'quote': 'quote',
  'quote_item': 'quote',
  'credit': 'credit',
  'payment': 'payment',
  'expense': 'expense',
  'task': 'task',
  'product': 'product',
  'vendor': 'vendor',
  'purchase_order': 'purchase_order',
  'purchase_order_item': 'purchase_order',
  'recurring_invoice': 'recurring_invoice',
  'recurring_invoice_item': 'recurring_invoice',
  'project': 'project',
};

/// The 28 reports we mirror from React (`useReports.ts`). Each entry carries
/// its endpoint, `supportsPreview`, the server-side `filterFields` the settings
/// panel renders, and `defaultFilterValues`. Field visibility mirrors
/// `react/src/pages/reports/common/hooks/useShowReportField.ts`.
const kReportDefinitions = <ReportDefinition>[
  // ─── Entity reports ───
  ReportDefinition(
    identifier: 'activity',
    category: ReportCategory.records,
    defaultRange: ReportDatePreset.thisYear,
    dateRangeKey: 'created_at',
    endpoint: '/api/v1/reports/activities',
    labelKey: 'activities',
    icon: EntityType.user,
    requiredPermission: 'view_reports',
    textColumnIds: {'date'},
    opensGrouped: false,
    filterFields: [ReportFilterField.dateRange, ReportFilterField.activityType],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'client',
    category: ReportCategory.records,
    defaultColumnIds: [
      'client.name',
      'client.number',
      'contact.email',
      'client.currency_id',
      'client.balance',
      'client.paid_to_date',
      'client.country_id',
    ],
    headlineMeasureIds: ['client.balance', 'client.paid_to_date'],
    starterViews: [
      ReportStarterView(labelKey: 'country', group: 'client.country_id'),
    ],
    opensGrouped: false,
    rowIdKey: 'client.id',
    rowRecordWire: 'client',
    dateRangeKey: 'created_at',
    optionalDateColumnId: 'client.created_at',
    endpoint: '/api/v1/reports/clients',
    labelKey: 'clients',
    icon: EntityType.client,
    requiredPermission: 'view_client',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {
      'date_range': 'all',
      'date_key': 'created_at',
      'include_deleted': false,
    },
  ),
  ReportDefinition(
    identifier: 'contact',
    category: ReportCategory.records,
    defaultColumnIds: [
      'client.name',
      'contact.first_name',
      'contact.last_name',
      'contact.email',
      'contact.phone',
    ],
    rowIdKey: 'client.id',
    rowRecordWire: 'client',
    dateRangeKey: 'created_at',
    optionalDateColumnId: 'contact.created_at',
    endpoint: '/api/v1/reports/contacts',
    labelKey: 'contacts',
    icon: EntityType.client,
    requiredPermission: 'view_client',
    filterFields: [ReportFilterField.dateRange],
    defaultFilterValues: {'date_range': 'all', 'date_key': 'created_at'},
  ),
  ReportDefinition(
    identifier: 'credit',
    category: ReportCategory.sales,
    defaultRange: ReportDatePreset.thisYear,
    defaultColumnIds: [
      'client.name',
      'credit.number',
      'credit.date',
      'credit.status',
      'credit.amount',
      'credit.balance',
    ],
    headlineMeasureIds: ['credit.amount', 'credit.balance'],
    starterViews: [
      ReportStarterView(
        labelKey: 'month',
        group: 'credit.date',
        subgroup: ReportSubgroup.month,
      ),
      ReportStarterView(labelKey: 'client', group: 'client.name'),
      ReportStarterView(labelKey: 'status', group: 'credit.status'),
    ],
    rowIdKey: 'credit.id',
    rowRecordWire: 'credit',
    dateRangeKey: 'created_at',
    endpoint: '/api/v1/reports/credits',
    labelKey: 'credits',
    icon: EntityType.credit,
    requiredPermission: 'view_credit',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.clientIdsMulti,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all', 'date_key': 'created_at'},
  ),
  ReportDefinition(
    identifier: 'document',
    category: ReportCategory.records,
    dateRangeKey: 'created_at',
    endpoint: '/api/v1/reports/documents',
    labelKey: 'documents',
    icon: EntityType.document,
    requiredPermission: 'view_reports',
    filterFields: [ReportFilterField.dateRange],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'expense',
    category: ReportCategory.expenses,
    defaultRange: ReportDatePreset.thisYear,
    defaultColumnIds: [
      'expense.number',
      'expense.date',
      'expense.category_id',
      'expense.vendor_id',
      'expense.public_notes',
      'expense.amount',
      'expense.tax_amount',
      'expense.net_amount',
    ],
    headlineMeasureIds: [
      'expense.amount',
      'expense.net_amount',
      'expense.tax_amount',
    ],
    starterViews: [
      ReportStarterView(
        labelKey: 'month',
        group: 'expense.date',
        subgroup: ReportSubgroup.month,
      ),
      ReportStarterView(labelKey: 'category', group: 'expense.category_id'),
      ReportStarterView(labelKey: 'vendor', group: 'expense.vendor_id'),
    ],
    rowIdKey: 'expense.id',
    rowRecordWire: 'expense',
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/expenses',
    labelKey: 'expenses',
    icon: EntityType.expense,
    requiredPermission: 'view_expense',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.clientsMulti,
      ReportFilterField.vendorsMulti,
      ReportFilterField.categoriesMulti,
      ReportFilterField.projectsMulti,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all', 'date_key': 'date'},
  ),
  ReportDefinition(
    identifier: 'invoice',
    category: ReportCategory.sales,
    defaultRange: ReportDatePreset.thisYear,
    defaultColumnIds: [
      'client.name',
      'invoice.number',
      'invoice.date',
      'invoice.due_date',
      'invoice.status',
      'invoice.amount',
      'invoice.balance',
      'invoice.paid_to_date',
    ],
    headlineMeasureIds: [
      'invoice.amount',
      'invoice.balance',
      'invoice.paid_to_date',
    ],
    starterViews: [
      ReportStarterView(
        labelKey: 'month',
        group: 'invoice.date',
        subgroup: ReportSubgroup.month,
      ),
      ReportStarterView(labelKey: 'client', group: 'client.name'),
      ReportStarterView(labelKey: 'status', group: 'invoice.status'),
    ],
    rowIdKey: 'invoice.id',
    rowRecordWire: 'invoice',
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/invoices',
    labelKey: 'invoices',
    icon: EntityType.invoice,
    requiredPermission: 'view_invoice',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.clientIdsMulti,
      ReportFilterField.template,
      ReportFilterField.pdfEmailAttachment,
      ReportFilterField.documentEmailAttachment,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all', 'date_key': 'date'},
  ),
  ReportDefinition(
    identifier: 'invoice_item',
    category: ReportCategory.sales,
    defaultRange: ReportDatePreset.thisYear,
    defaultColumnIds: [
      'client.name',
      'invoice.number',
      'invoice.date',
      'item.product_key',
      'item.notes',
      'item.quantity',
      'item.cost',
      'item.line_total',
    ],
    headlineMeasureIds: ['item.line_total', 'item.quantity'],
    starterViews: [
      ReportStarterView(labelKey: 'product', group: 'item.product_key'),
      ReportStarterView(
        labelKey: 'month',
        group: 'invoice.date',
        subgroup: ReportSubgroup.month,
      ),
      ReportStarterView(labelKey: 'client', group: 'client.name'),
    ],
    rowIdKey: 'invoice.id',
    rowRecordWire: 'invoice',
    lineItemPrefix: 'item',
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/invoice_items',
    labelKey: 'invoice_items',
    icon: EntityType.invoice,
    requiredPermission: 'view_invoice',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.clientIdsMulti,
      ReportFilterField.productKey,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'purchase_order',
    category: ReportCategory.expenses,
    defaultRange: ReportDatePreset.thisYear,
    defaultColumnIds: [
      'vendor.name',
      'purchase_order.number',
      'purchase_order.date',
      'purchase_order.due_date',
      'purchase_order.status',
      'purchase_order.amount',
      'purchase_order.balance',
    ],
    headlineMeasureIds: ['purchase_order.amount', 'purchase_order.balance'],
    starterViews: [
      ReportStarterView(
        labelKey: 'month',
        group: 'purchase_order.date',
        subgroup: ReportSubgroup.month,
      ),
      ReportStarterView(labelKey: 'vendor', group: 'vendor.name'),
      ReportStarterView(labelKey: 'status', group: 'purchase_order.status'),
    ],
    rowIdKey: 'purchase_order.id',
    rowRecordWire: 'purchase_order',
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/purchase_orders',
    labelKey: 'purchase_orders',
    icon: EntityType.purchaseOrder,
    requiredPermission: 'view_purchase_order',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'purchase_order_item',
    category: ReportCategory.expenses,
    defaultRange: ReportDatePreset.thisYear,
    defaultColumnIds: [
      'vendor.name',
      'purchase_order.number',
      'purchase_order.date',
      'item.product_key',
      'item.notes',
      'item.quantity',
      'item.cost',
      'item.line_total',
    ],
    headlineMeasureIds: ['item.line_total', 'item.quantity'],
    starterViews: [
      ReportStarterView(labelKey: 'product', group: 'item.product_key'),
      ReportStarterView(
        labelKey: 'month',
        group: 'purchase_order.date',
        subgroup: ReportSubgroup.month,
      ),
      ReportStarterView(labelKey: 'vendor', group: 'vendor.name'),
    ],
    rowIdKey: 'purchase_order.id',
    rowRecordWire: 'purchase_order',
    lineItemPrefix: 'item',
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/purchase_order_items',
    labelKey: 'purchase_order_items',
    icon: EntityType.purchaseOrder,
    requiredPermission: 'view_purchase_order',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.productKey,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'quote',
    category: ReportCategory.sales,
    defaultRange: ReportDatePreset.thisYear,
    defaultColumnIds: [
      'client.name',
      'quote.number',
      'quote.date',
      'quote.due_date',
      'quote.status',
      'quote.amount',
    ],
    headlineMeasureIds: ['quote.amount'],
    starterViews: [
      ReportStarterView(
        labelKey: 'month',
        group: 'quote.date',
        subgroup: ReportSubgroup.month,
      ),
      ReportStarterView(labelKey: 'client', group: 'client.name'),
      ReportStarterView(labelKey: 'status', group: 'quote.status'),
    ],
    rowIdKey: 'quote.id',
    rowRecordWire: 'quote',
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/quotes',
    labelKey: 'quotes',
    icon: EntityType.quote,
    requiredPermission: 'view_quote',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.clientIdsMulti,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'quote_item',
    category: ReportCategory.sales,
    defaultRange: ReportDatePreset.thisYear,
    defaultColumnIds: [
      'client.name',
      'quote.number',
      'quote.date',
      'item.product_key',
      'item.notes',
      'item.quantity',
      'item.cost',
      'item.line_total',
    ],
    headlineMeasureIds: ['item.line_total', 'item.quantity'],
    starterViews: [
      ReportStarterView(labelKey: 'product', group: 'item.product_key'),
      ReportStarterView(
        labelKey: 'month',
        group: 'quote.date',
        subgroup: ReportSubgroup.month,
      ),
      ReportStarterView(labelKey: 'client', group: 'client.name'),
    ],
    rowIdKey: 'quote.id',
    rowRecordWire: 'quote',
    lineItemPrefix: 'item',
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/quote_items',
    labelKey: 'quote_items',
    icon: EntityType.quote,
    requiredPermission: 'view_quote',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.clientIdsMulti,
      ReportFilterField.productKey,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'recurring_invoice',
    category: ReportCategory.sales,
    defaultColumnIds: [
      'client.name',
      'recurring_invoice.number',
      'recurring_invoice.frequency_id',
      'recurring_invoice.next_send_date',
      'recurring_invoice.remaining_cycles',
      'recurring_invoice.status',
      'recurring_invoice.amount',
    ],
    headlineMeasureIds: ['recurring_invoice.amount'],
    starterViews: [
      ReportStarterView(labelKey: 'client', group: 'client.name'),
      ReportStarterView(
        labelKey: 'frequency',
        group: 'recurring_invoice.frequency_id',
      ),
      ReportStarterView(labelKey: 'status', group: 'recurring_invoice.status'),
    ],
    opensGrouped: false,
    rowIdKey: 'recurring_invoice.id',
    rowRecordWire: 'recurring_invoice',
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/recurring_invoices',
    labelKey: 'recurring_invoices',
    icon: EntityType.recurringInvoice,
    requiredPermission: 'view_recurring_invoice',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.clientIdsMulti,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'recurring_invoice_item',
    category: ReportCategory.sales,
    defaultColumnIds: [
      'client.name',
      'recurring_invoice.number',
      'item.product_key',
      'item.notes',
      'item.quantity',
      'item.cost',
      'item.line_total',
    ],
    headlineMeasureIds: ['item.line_total', 'item.quantity'],
    starterViews: [
      ReportStarterView(labelKey: 'product', group: 'item.product_key'),
      ReportStarterView(labelKey: 'client', group: 'client.name'),
    ],
    opensGrouped: false,
    // `RecurringInvoiceItemExport::buildRow` reads the parent document off
    // the `invoice.` prefix, not `recurring_invoice.`.
    rowIdKey: 'invoice.id',
    rowRecordWire: 'recurring_invoice',
    lineItemPrefix: 'item',
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/recurring_invoice_items',
    labelKey: 'recurring_invoice_items',
    icon: EntityType.recurringInvoice,
    requiredPermission: 'view_recurring_invoice',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.clientIdsMulti,
      ReportFilterField.productKey,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'payment',
    category: ReportCategory.sales,
    defaultRange: ReportDatePreset.thisYear,
    defaultColumnIds: [
      'client.name',
      'payment.number',
      'payment.date',
      'payment.method',
      'payment.status',
      'payment.amount',
      'payment.applied',
      'payment.refunded',
    ],
    headlineMeasureIds: [
      'payment.amount',
      'payment.applied',
      'payment.refunded',
    ],
    starterViews: [
      ReportStarterView(
        labelKey: 'month',
        group: 'payment.date',
        subgroup: ReportSubgroup.month,
      ),
      ReportStarterView(labelKey: 'client', group: 'client.name'),
      ReportStarterView(labelKey: 'payment_type', group: 'payment.method'),
    ],
    rowIdKey: 'payment.id',
    rowRecordWire: 'payment',
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/payments',
    labelKey: 'payments',
    icon: EntityType.payment,
    requiredPermission: 'view_payment',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.clientIdsMulti,
      ReportFilterField.tagsMulti,
    ],
    defaultFilterValues: {'date_range': 'all', 'date_key': 'date'},
  ),
  ReportDefinition(
    identifier: 'product',
    category: ReportCategory.records,
    defaultColumnIds: [
      'product_key',
      'notes',
      'price',
      'cost',
      'quantity',
      'in_stock_quantity',
      'stock_value',
    ],
    headlineMeasureIds: ['stock_value', 'in_stock_quantity'],
    rowIdKey: 'product.hashed_id',
    rowRecordWire: 'product',
    dateRangeKey: 'created_at',
    optionalDateColumnId: 'product.created_at',
    endpoint: '/api/v1/reports/products',
    labelKey: 'products',
    icon: EntityType.product,
    requiredPermission: 'view_product',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'product_sales',
    category: ReportCategory.sales,
    defaultRange: ReportDatePreset.thisYear,
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/product_sales',
    labelKey: 'product_sales',
    icon: EntityType.product,
    requiredPermission: 'view_product',
    supportsPreview: false,
    readsAsDocument: true,
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.clientSingle,
      ReportFilterField.productKey,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'task',
    category: ReportCategory.time,
    defaultRange: ReportDatePreset.thisYear,
    defaultColumnIds: [
      'client.name',
      'task.number',
      'task.description',
      'task.project_id',
      'task.user_id',
      'task.start_date',
      'task.duration',
      'task.status_id',
    ],
    headlineMeasureIds: ['task.duration'],
    starterViews: [
      ReportStarterView(labelKey: 'project', group: 'task.project_id'),
      ReportStarterView(labelKey: 'user', group: 'task.user_id'),
      ReportStarterView(
        labelKey: 'month',
        group: 'task.start_date',
        subgroup: ReportSubgroup.month,
      ),
      ReportStarterView(labelKey: 'client', group: 'client.name'),
    ],
    rowIdKey: 'task.id',
    rowRecordWire: 'task',
    oncePerRecordColumnIds: {'task.estimated_duration'},
    dateRangeKey: 'calculated_start_date',
    endpoint: '/api/v1/reports/tasks',
    labelKey: 'tasks',
    icon: EntityType.task,
    requiredPermission: 'view_task',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.status,
      ReportFilterField.clientIdsMulti,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'vendor',
    category: ReportCategory.expenses,
    defaultColumnIds: [
      'vendor.name',
      'vendor.number',
      'vendor_contact.email',
      'vendor.phone',
      'vendor.city',
      'vendor.country_id',
      'vendor.currency',
    ],
    rowIdKey: 'vendor.id',
    rowRecordWire: 'vendor',
    dateRangeKey: 'created_at',
    optionalDateColumnId: 'vendor.created_at',
    endpoint: '/api/v1/reports/vendors',
    labelKey: 'vendors',
    icon: EntityType.vendor,
    requiredPermission: 'view_vendor',
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.tagsMulti,
      ReportFilterField.includeDeleted,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'project',
    category: ReportCategory.time,
    endpoint: '/api/v1/reports/projects',
    labelKey: 'projects',
    icon: EntityType.project,
    requiredPermission: 'view_project',
    supportsPreview: false,
    filterFields: [
      ReportFilterField.clientsMulti,
      ReportFilterField.projectsMulti,
      ReportFilterField.tagsMulti,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  // ─── Financial / aggregate reports ───
  ReportDefinition(
    identifier: 'profitloss',
    category: ReportCategory.financial,
    defaultRange: ReportDatePreset.thisYear,
    endpoint: '/api/v1/reports/profitloss',
    labelKey: 'profit_and_loss',
    icon: EntityType.invoice,
    requiredPermission: 'view_reports',
    supportsPreview: false,
    readsAsDocument: true,
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.isIncomeBilled,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'aged_receivable_detailed_report',
    category: ReportCategory.receivables,
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/ar_detail_report',
    labelKey: 'aged_receivable_detailed_report',
    icon: EntityType.invoice,
    requiredPermission: 'view_reports',
    supportsPreview: false,
    readsAsDocument: true,
    filterFields: [ReportFilterField.dateRange, ReportFilterField.clientSingle],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'aged_receivable_summary_report',
    category: ReportCategory.receivables,
    // No `dateRangeKey`: `ARSummaryReport` declares `$date_key = 'date'` and
    // lists the three date params in its input contract, but never calls
    // `addDateRange` — its only date predicate is the aging buckets'
    // `whereBetween('due_date', …)`. Same defect as `project`; naming a
    // column the server ignores is exactly what this field exists to stop.
    endpoint: '/api/v1/reports/ar_summary_report',
    labelKey: 'aged_receivable_summary_report',
    icon: EntityType.invoice,
    requiredPermission: 'view_reports',
    supportsPreview: false,
    readsAsDocument: true,
    filterFields: [],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'client_balance_report',
    category: ReportCategory.receivables,
    dateRangeKey: 'created_at',
    endpoint: '/api/v1/reports/client_balance_report',
    labelKey: 'client_balance_report',
    icon: EntityType.client,
    requiredPermission: 'view_reports',
    supportsPreview: false,
    readsAsDocument: true,
    filterFields: [ReportFilterField.dateRange],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'client_sales_report',
    category: ReportCategory.sales,
    defaultRange: ReportDatePreset.thisYear,
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/client_sales_report',
    labelKey: 'client_sales_report',
    icon: EntityType.client,
    requiredPermission: 'view_reports',
    supportsPreview: false,
    readsAsDocument: true,
    filterFields: [ReportFilterField.dateRange],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'tax_summary_report',
    category: ReportCategory.financial,
    defaultRange: ReportDatePreset.thisYear,
    dateRangeKey: 'date',
    endpoint: '/api/v1/reports/tax_summary_report',
    labelKey: 'tax_summary_report',
    icon: EntityType.invoice,
    requiredPermission: 'view_reports',
    supportsPreview: false,
    readsAsDocument: true,
    filterFields: [ReportFilterField.dateRange, ReportFilterField.clientSingle],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'tax_period_report',
    category: ReportCategory.financial,
    endpoint: '/api/v1/reports/tax_period_report',
    labelKey: 'tax_period_report',
    icon: EntityType.invoice,
    requiredPermission: 'view_reports',
    supportsPreview: false,
    filterFields: [
      ReportFilterField.dateRange,
      ReportFilterField.clientSingle,
      ReportFilterField.isIncomeBilled,
    ],
    defaultFilterValues: {'date_range': 'all'},
  ),
  ReportDefinition(
    identifier: 'user_sales_report',
    category: ReportCategory.sales,
    defaultRange: ReportDatePreset.thisYear,
    dateRangeKey: 'created_at',
    endpoint: '/api/v1/reports/user_sales_report',
    labelKey: 'user_sales_report',
    icon: EntityType.user,
    requiredPermission: 'view_reports',
    supportsPreview: false,
    readsAsDocument: true,
    filterFields: [ReportFilterField.dateRange, ReportFilterField.clientSingle],
    defaultFilterValues: {'date_range': 'all'},
  ),
];

/// Look up a definition by its wire identifier. Throws on miss — the caller
/// should be choosing from [kReportDefinitions] anyway.
ReportDefinition reportDefinitionFor(String identifier) {
  for (final def in kReportDefinitions) {
    if (def.identifier == identifier) return def;
  }
  throw ArgumentError.value(identifier, 'identifier', 'Unknown report');
}

/// Default report identifier on first-ever load. Matches admin-portal's
/// `_initialState` (`kReportClient`) and React's [`Identifier`] union.
const String kDefaultReportIdentifier = 'client';
