// Generates every DERIVED app-icon raster from the single 1024x1024 macOS
// app-icon source: the multi-size Windows .ico, the MSIX store logo, the four
// web/PWA icons, and the Snap/AppImage icon.
//
//   dart run tools/gen_app_icons.dart
//
// Re-run after any logo change and commit the outputs. Only iOS/macOS (which
// consume `AppIcon.icon/Assets/Image.png` directly) and Android (generated by
// flutter_launcher_icons from assets/images/icon.png) are outside its scope.
//
// The source is a macOS "glass" alpha matte, NOT a finished raster: its RGB is
// entirely black and the envelope shape lives only in the ALPHA channel (icon.json
// sets glass:true — macOS fills the matte with the system material). No other
// platform has such a treatment, so resizing the matte straight through draws an
// all-dark icon with no white anywhere. We therefore BAKE the alpha into real
// pixels — white where the source is transparent (the envelope), black where
// opaque (linework + background). Do NOT swap in assets/images/icon.png: it's
// circular (a mask is baked in) and only 152px, which would look wrong and soft.
//
// Two shapes come out of that bake:
//
//   * DISC — the envelope on a black circle, transparent outside. This is the
//     shape the v1 app (admin-portal) has always shipped on Windows, and it's
//     what a Windows 11 taskbar needs: MSIX draws the app icon UNPLATED, so a
//     full-bleed opaque square just reads as a dark box. MSIX tiles declare
//     BackgroundColor="transparent", so the system accent shows behind the disc.
//   * MASKABLE — the envelope on an opaque black square, inset so the mark stays
//     inside the PWA safe zone (a centered circle of 80% of the canvas) that
//     Android/Chrome crop maskable icons to.
//
// One artifact to know about: the matte has a 1px fully-transparent frame around
// the whole canvas, which bakes to a WHITE hairline. `_clampBorder` blacks it out
// before anything else — otherwise every output ships a white edge.

import 'dart:io';
import 'dart:math' as math;

import 'package:image/image.dart';

const _source = 'macos/AppIcon.icon/Assets/Image.png';

const _icoOutput = 'windows/runner/resources/app_icon.ico';
// Full-res disc for `msix_config.logo_path` — msix generates the whole
// AppxManifest visual-asset tree (Start tile, taskbar, Search, Store logo,
// splash) from this one file; without it the package ships the msix package's
// default FLUTTER-logo assets, which is exactly what issue #25 reported.
const _storeLogoOutput = 'windows/runner/resources/store_logo.png';
const _snapOutput = 'snap/gui/invoiceninja.png';
const _webIconDir = 'web/icons';

// Sizes Windows picks between for the taskbar, Alt-Tab, Explorer and title bar.
const _icoSizes = [16, 24, 32, 48, 64, 128, 256];

/// Inset, in source pixels, of the disc from the canvas edge. Two is enough to
/// swallow the 1px transparent frame in the matte at every downsampled size.
const _discInset = 2;

/// Scale applied to the mark for maskable icons. The envelope's far corner sits
/// at 0.820 of the half-width, and the maskable safe circle has a radius of 0.8
/// of the half-width, so anything at or below 0.976 is safe; 0.95 leaves margin.
const _maskableScale = 0.95;

void main() {
  final src = decodePng(File(_source).readAsBytesSync());
  if (src == null) {
    stderr.writeln('Could not decode $_source');
    exit(1);
  }

  final square = _bake(src);
  final disc = _applyDisc(square);

  _writeIco(_icoOutput, disc, _icoSizes);
  _writePng(_storeLogoOutput, disc);
  _writePng(_snapOutput, _resize(disc, 512));

  for (final size in [192, 512]) {
    _writePng('$_webIconDir/Icon-$size.png', _resize(disc, size));
    _writePng('$_webIconDir/Icon-maskable-$size.png', _maskable(square, size));
  }
}

/// Bakes the alpha matte into an opaque grayscale square: the envelope body is
/// the TRANSPARENT negative space (alpha 0) and the surround + flap linework are
/// opaque, so the gray value is the INVERTED alpha (255 - a).
Image _bake(Image src) {
  final baked = Image(width: src.width, height: src.height, numChannels: 4);
  for (final p in src) {
    final v = 255 - p.a.toInt();
    baked.setPixelRgba(p.x, p.y, v, v, v, 255);
  }
  return _clampBorder(baked, _discInset);
}

/// Blacks out the outer [width]-pixel ring. The matte's fully-transparent 1px
/// frame bakes to white; left in, it survives downsampling as a bright hairline
/// around every icon.
Image _clampBorder(Image image, int width) {
  for (final p in image) {
    if (p.x < width ||
        p.y < width ||
        p.x >= image.width - width ||
        p.y >= image.height - width) {
      image.setPixelRgba(p.x, p.y, 0, 0, 0, p.a);
    }
  }
  return image;
}

/// Masks the square bake to an inscribed circle, transparent outside. RGB is
/// left untouched (black) beyond the edge so `copyResize`, which averages
/// straight RGB rather than premultiplied, bleeds black into the antialiased
/// rim instead of a lighter fringe.
Image _applyDisc(Image square) {
  final out = square.clone();
  final cx = (out.width - 1) / 2.0;
  final cy = (out.height - 1) / 2.0;
  final radius = math.min(cx, cy) - _discInset;
  for (final p in out) {
    final dx = p.x - cx;
    final dy = p.y - cy;
    final d = math.sqrt(dx * dx + dy * dy);
    // 1px linear falloff at the rim; the 1024 -> N downsample smooths the rest.
    final coverage = (radius - d).clamp(0.0, 1.0);
    p.a = (coverage * 255).round();
  }
  return out;
}

/// Opaque black square with the mark inset into the PWA maskable safe zone.
/// The surround is already black, so compositing the scaled bake onto a black
/// canvas is seamless — and both are opaque, so the result is too (a maskable
/// icon must be, since the launcher crops it to a shape of its choosing).
Image _maskable(Image square, int size) {
  final canvas = Image(width: size, height: size, numChannels: 4);
  fill(canvas, color: ColorRgba8(0, 0, 0, 255));
  compositeImage(
    canvas,
    _resize(square, (size * _maskableScale).round()),
    center: true,
  );
  return canvas;
}

Image _resize(Image image, int size) => copyResize(
  image,
  width: size,
  height: size,
  // Box filter — the right choice when every output is a downsample.
  interpolation: Interpolation.average,
);

/// `IcoEncoder.encodeImages` writes one ICO directory entry per supplied image
/// (each keeps its own width/height) — unlike the top-level `encodeIco()`
/// helper, which only emits a single size.
void _writeIco(String path, Image source, List<int> sizes) {
  final frames = [for (final size in sizes) _resize(source, size)];
  File(path).writeAsBytesSync(IcoEncoder().encodeImages(frames));
  stdout.writeln('Wrote $path (${sizes.length} sizes: $sizes)');
}

void _writePng(String path, Image image) {
  File(path).writeAsBytesSync(encodePng(image));
  stdout.writeln('Wrote $path (${image.width}x${image.height})');
}
